image:
  file: .gitpod.Dockerfile

tasks:
  - init: pipenv install
    command: python manage.py runserver 0.0.0.0:8000
  - command: redis-server


vscode:
  extensions:
    - ms-python.python
    - GitHub.github-vscode-theme
    - eamodio.gitlens
    - ms-dotnettools.csharp

# ports:
#   - port: 8000
#     # onOpen: open-browser
