services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    expose:
      - 5432
    # networks:
    #   - stats_network
  django:
    build: .
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    depends_on:
      - postgres
    # networks:
    #   - stats_network
  
# networks:
#   stats_network:
#     external: true