services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    expose:
      - 5432
  django:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
