# Generated by Django 3.2.6 on 2021-08-26 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The full name of the player.', max_length=255)),
                ('position', models.CharField(choices=[('RB', 'Runningback'), ('QB', 'Quarterback'), ('WR', 'Wide Receiver'), ('FB', 'Fullback'), ('P', 'Punter'), ('TE', 'Tightend'), ('NT', 'Nose Tackle'), ('DB', 'Defensiveback'), ('SS', 'Strong Safety'), ('K', 'Kicker')], help_text="The player's position", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The long form team name (ex. Seattle Seahawks)', max_length=255)),
                ('abbreviation', models.CharField(help_text='The abbreviation of the team (ex. SEA)', max_length=255)),
                ('nfl_com_link', models.CharField(help_text='The nfl.com team website address.', max_length=255)),
                ('logo', models.CharField(help_text='The wikipedia hosted logo', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('attempts_game', models.FloatField(default=0)),
                ('yards', models.IntegerField(default=0)),
                ('average', models.FloatField(default=0)),
                ('yards_game', models.FloatField(default=0)),
                ('touchdowns', models.PositiveIntegerField(default=0)),
                ('longgains', models.PositiveIntegerField(default=0)),
                ('longgains_team', models.BooleanField(default=False)),
                ('first_down', models.PositiveIntegerField(default=0)),
                ('first_down_conversion', models.FloatField()),
                ('twenty_plus', models.PositiveIntegerField(default=0)),
                ('forty_plus', models.PositiveIntegerField(default=0)),
                ('fumbles', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(help_text="The player's stats for a team", through='core.Stat', to='core.Team'),
        ),
    ]
