# Generated by Django 3.2.5 on 2021-08-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='image',
            field=models.ImageField(default='', upload_to='armor/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='image',
            field=models.ImageField(default='', upload_to='weapon/'),
            preserve_default=False,
        ),
    ]
