# Generated by Django 3.2.6 on 2021-08-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('N', 'North'), ('S', 'Soouth'), ('E', 'East'), ('W', 'West')], default='', help_text='The division the team is currently in.', max_length=255),
            preserve_default=False,
        ),
    ]
