# Generated by Django 3.2.6 on 2021-08-29 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='core.player'),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='core.season'),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='core.team'),
        ),
    ]
