# Generated by Django 3.2.6 on 2021-08-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210829_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='playerseasonstats',
            options={'ordering': ('player__position', 'player__name')},
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='longgains_team',
            new_name='longgest_gains_touchdown',
        ),
    ]
