# Generated by Django 3.2.5 on 2021-08-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210802_0449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armor',
            old_name='enery',
            new_name='energy',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='enery',
            new_name='energy',
        ),
    ]
