# Generated by Django 3.2.6 on 2021-08-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210830_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='longgains',
            new_name='longgest_gains',
        ),
    ]
