# Generated by Django 3.2.5 on 2021-08-02 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210802_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armor',
            old_name='durabiltiy',
            new_name='durability',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='durabiltiy',
            new_name='durability',
        ),
    ]
