# Generated by Django 3.2.6 on 2021-08-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_longgains_playerseasonstats_longgest_gains'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='longgest_gains',
            new_name='longest_gains',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='longgest_gains_touchdown',
            new_name='longest_gains_touchdown',
        ),
    ]
