# Generated by Django 3.2.5 on 2021-08-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210802_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='armor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='weapon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
