# Generated by Django 3.2.7 on 2021-09-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210830_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerseasonstats',
            name='first_down_conversion',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], help_text='The division the team is currently in.', max_length=255),
        ),
    ]
