# Generated by Django 3.2.5 on 2021-08-02 22:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210802_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 22, 27, 57, 858355, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 22, 28, 4, 253314, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='armor',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
