# Generated by Django 3.2.5 on 2021-08-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210802_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
