# Generated by Django 3.2.5 on 2021-08-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210802_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='prefab_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='prefab_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
